[package]
name = "xor_and_shit"
version = "0.1.0"
authors = ["braindead <braindeaded@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
